name: "🚀 Publish"

on:
    push:
        branches: main

jobs:
    release:
        name: publish
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@master
            - name: node
              uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
            - name: publish
              run: npm publish --access public
              working-directory: thelounge-theme-flat-dark
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
